# 1. 可执行文件输出目录（优先用这个，动态库也会默认放这里）
# 格式：构建目录/平台/配置/bin
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY
        "${CMAKE_BINARY_DIR}/${CMAKE_SYSTEM_NAME}/${CMAKE_BUILD_TYPE}/bin"
)
# 针对多配置生成器（如 MSVC、Xcode），需添加 CONFIG 后缀（Debug/Release 自动区分）
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG
        "${CMAKE_BINARY_DIR}/${CMAKE_SYSTEM_NAME}/Debug/bin"
)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE
        "${CMAKE_BINARY_DIR}/${CMAKE_SYSTEM_NAME}/Release/bin"
)

# 2. 静态库/动态库输出目录（若需和可执行文件分开，单独设置）
# 静态库（.lib/.a）：CMAKE_ARCHIVE_OUTPUT_DIRECTORY
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY
        "${CMAKE_BINARY_DIR}/${CMAKE_SYSTEM_NAME}/${CMAKE_BUILD_TYPE}/lib"
)
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_DEBUG
        "${CMAKE_BINARY_DIR}/${CMAKE_SYSTEM_NAME}/Debug/lib"
)
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE
        "${CMAKE_BINARY_DIR}/${CMAKE_SYSTEM_NAME}/Release/lib"
)

# 动态库（.so/.dylib，Linux/macOS 专用，Windows 动态库仍用 RUNTIME 目录）
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY
        "${CMAKE_BINARY_DIR}/${CMAKE_SYSTEM_NAME}/${CMAKE_BUILD_TYPE}/lib"
)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_DEBUG
        "${CMAKE_BINARY_DIR}/${CMAKE_SYSTEM_NAME}/Debug/lib"
)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE
        "${CMAKE_BINARY_DIR}/${CMAKE_SYSTEM_NAME}/Release/lib"
)